version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: citizenui-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: citizenui
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # CitizenUI Application
  app:
    build: .
    container_name: citizenui-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_USER=postgres
      - DB_HOST=postgres
      - DB_NAME=citizenui
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - DB_SSL=false
      - JWT_SECRET=development-jwt-secret-change-in-production
      - NEXT_PUBLIC_API_URL=/api
      - NEXT_PUBLIC_BASE_URL=http://localhost:3000
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data:
    driver: local 